In [7]:
def foo(x):
    return x+1

In [3]:
foo

<function __main__.foo(x)>

In [10]:
foo(1)

3

In [9]:
def foo(x):
    return x+2

In [8]:
foo(1)

2

In [11]:
_ = 1

In [12]:
_

1

In [149]:
a = np.array([[0,0],[1,1],[2,2],[3,3],[4,5],[6,7]])
n = a.shape[0]
n

6

In [154]:
indices = np.random.choice(n, 2, replace=False)
print(indices)
b = np.take(a, indices, axis=0)
b

[1 2]


array([[1, 1],
       [2, 2]])

In [158]:
print(np.take([1,2,3,4,5,6,7,8], [1,3,2], axis=0))

[2 4 3]


In [159]:
c = np.array([6,32,7,1,-8,9])

In [162]:
print(np.argmax(c))

1


In [167]:
d = [x+1 for x in c if x%2==0]

In [168]:
c, d

(array([ 6, 32,  7,  1, -8,  9]), [7, 33, -7])

In [191]:
y = np.arange(3).reshape((3,1))
y

array([[0],
       [1],
       [2]])

In [179]:
x = np.arange(6).reshape((2,3))
x

array([[0, 1, 2],
       [3, 4, 5]])

In [182]:
print(x.dot(y).shape)

(2, 1)


In [183]:
print(x.T)

[[0 3]
 [1 4]
 [2 5]]


In [189]:
yx = y.T.dot(x.T)
print(yx.shape)

(1, 2)
